### ISSUE TITLE
Latest doesn't always see app updates from the Mac App Store

### ISSUE THREAD

**Issue by helingai** [mangerlahn/Latest#129] opened 2022-01-18 19:51 UTC
See the screenshot for an example. Here Latest doesn't see the new Microsoft Word, but it's listed in the App Store.

![Screen Shot 2022-01-18 at 14 50 51](https://user-images.githubusercontent.com/51121379/150008600-d05a3428-2ea0-44ce-a7e0-290d47ba1b09.png)

**Comment by mangerlahn** [comment] 2022-03-12 10:32
Thanks for the report. This is a duplicate of #106 which I just fixed. It will be available in the next update!

**Closed by mangerlahn** 2022-03-12 10:32 UTC
