### ISSUE TITLE
Auto Start

### ISSUE THREAD

**Issue by joopklaassen** [mangerlahn/Latest#259] opened 2023-03-13 12:19 UTC
Would it be possible to make the app automatically launch on a set time.
Like very monday at 15.00?

This way I don't have to think about it and my machine will stay up to date.

Having an update all button would be great too. (i know it is in the menu, but it could be next to the refresh button for instance)

thanks for this piece of software!! 

Cheers!

**Comment by hstriepe** [comment] 2023-07-07 19:50
You can add it to the Login items.

**Comment by mangerlahn** [comment] 2023-07-30 21:33
There are plans to restructure the app to operate as a background service that can run periodically every hour, day or week, depending on user preference. The issue for this is #53. I hope to get around to doing this some day..

**Comment by mangerlahn** [comment] 2023-07-30 21:36
The Update All button should be right next to the refresh button. I need to think of a better icon, it looks like a simple update button 🙈

**Comment by mangerlahn** [comment] 2023-08-28 19:52
Duplicate of #53

**Closed by mangerlahn** 2023-08-28 19:52 UTC
