### ISSUE TITLE
Add French Localization

### ISSUE THREAD

**Issue by flavienbonvin** [mangerlahn/Latest#81] opened 2020-05-08 06:23 UTC
Latest version: Version 0.6.3 (370)

I live in Switzerland and the country has 4 national languages, French, German, Italian an Romansh. 

The application is in German but I live in the French speaking part of the country and would love to have the app in French. 

Why the application does not follow the system language? Are the French translation missing (if that's the case I could help with them)?

**Comment by gingerbeardman** [comment] 2020-05-08 08:04
Yes, only English (default) and German (localisation) so far.

https://github.com/mangerlahn/Latest/tree/master/Latest/Resources

You'll need to create a duplicate of the German localisation folder for French and modify the strings file to suit.

**Comment by flavienbonvin** [comment] 2020-05-08 08:38
Ok, added the French translation and created a pull request: https://github.com/mangerlahn/Latest/pull/82

**Closed** 2020-05-30 08:00 UTC
Labels: enhancement
