### ISSUE TITLE
Errors in updates tracking from brew

### ISSUE THREAD

**Issue by Drugsosos** [mangerlahn/Latest#289] opened 2023-11-28 10:12 UTC
- I have the last version of `Warp`, but `latest` thinks it's 0.1.0 version
- I use [`brew-cask-upgrade`](https://github.com/buo/homebrew-cask-upgrade) for upgrading casks and pinning some of them.
One of pinned ones is `Insomnia` and `latest` thinks it's up to date. I don't think it was intentional

<img width="413" alt="image" src="https://github.com/mangerlahn/Latest/assets/44712637/0fd46ea3-756f-46ac-a43c-e2caf20d9da1">

<img width="411" alt="image" src="https://github.com/mangerlahn/Latest/assets/44712637/03eff19e-1daa-4370-aac3-d8b34a2017e5">

---

Version 0.10 (1111)

**Comment by infonotarydev** [comment] 2023-11-28 14:20
I also have that issue
<img width="277" alt="SCR-20231128-oikn" src="https://github.com/mangerlahn/Latest/assets/16919892/3f4204a2-7528-49f2-a2a4-181fea7a085f">
Also for some apps, like in the case of Sublime, the version is the same but not parsed ok. Other times, like Spotify or IntelliJ, the app versions has variations that are not accepted.

**Comment by mangerlahn** [comment] 2023-11-28 18:51
Thanks for these reports! Ill look into them

**Comment by JLP04** [comment] 2023-11-28 21:13
I'm seeing this too. It might also be nice if there was a setting to hide updates fetched from brew (for those of us who check brew-cask manually anyway).

**Comment by mangerlahn** [comment] 2023-11-29 11:49
@JLP04 I am not sure if that would make sense. See my comment [here](https://github.com/mangerlahn/Latest/issues/288#issuecomment-1831744344), I hope this resolves soon.

**Comment by JLP04** [comment] 2023-11-29 21:05
I figured it was using the API, I think it'll be better once the false positives are fixed.

**Comment by mangerlahn** [comment] 2023-12-02 21:22
Closing this as duplicate of https://github.com/mangerlahn/Latest/issues/297. I added all apps brought up here to the list I maintain there. Thanks for reporting!

**Closed by mangerlahn** 2023-12-02 21:22 UTC
Labels: bug
