### ISSUE TITLE
Include Homebrew updates

### ISSUE THREAD

**Issue by mpwg** [mangerlahn/Latest#262] opened 2023-06-20 05:02 UTC
i have several [Homebrew](https://brew.sh) stuff installed.

It would be nice if Latest could:
1. List all Homebrew updates
2. offer to install them as well

**Comment by mangerlahn** [comment] 2023-06-21 09:29
I have a prototype laying around for over half a year now on my machine, just need some time to actually finish this 😅

**Comment by mangerlahn** [comment] 2023-06-21 09:30
This appears to be a duplicate of #45. I would focus on casks at the moment, since Latest is a very UI-centric app.

**Closed by mangerlahn** 2023-06-21 09:30 UTC
