### ISSUE TITLE
version number for iPad app is displayed

### ISSUE THREAD

**Issue by mackuba** [mangerlahn/Latest#113] opened 2021-02-07 20:20 UTC
Latest shows that I can update the app "Graphic" from 3.1 to 3.5.2. However, 3.1 is the latest available version. 3.5.2 is the latest version of the iPad counterpart of the same app.

I've checked this in Xcode and it seems that the problem is that the app makes a call to:

https://itunes.apple.com/lookup?bundleId=com.indeeo.idraw&country=PL&entity=macSoftware&limit=1

and this URL returns the iPad app, even though it explicitly says "macSoftware" there. Is there any way to force it to return the Mac app's info?

Here's the Mac app: https://apps.apple.com/us/app/graphic/id404705039?mt=12
And here's the iPad one: https://apps.apple.com/us/app/graphic-for-ipad/id363317633

**Comment by mangerlahn** [comment] 2021-02-07 22:02
Thank you for writing and digging through the problem. This is a duplicate of #106.
I don't think there is anything we can do for now. It is probably on Apple to fix its API.

You can file a radar/feedback though :)

**Closed** 2021-02-07 22:13 UTC

**Comment by mangerlahn** [comment] 2021-02-07 22:24
I am closing this as a duplicate for now :)
