### ISSUE TITLE
App crashes if there is no internet connection

### ISSUE THREAD

**Issue by phw-lopa** [mangerlahn/Latest#380] opened 2024-05-30 15:30 UTC
When I have no internet connection, the app crashes without even showing a window.

**Comment by tomkoi** [comment] 2024-06-03 17:54
same here, but i do have internet connection
on other mac no issues, not sure why it's happened

**Comment by mangerlahn** [comment] 2024-06-04 09:11
Thank you for the report. This is a duplicate of #340 and will be resolved in the next update :)

**Closed as completed by mangerlahn** 2024-06-04 09:11 UTC
