### ISSUE TITLE
Update Homebrew-based updates within Latest

### ISSUE THREAD

**Issue by Harry0275** [mangerlahn/Latest#301] opened 2023-12-01 08:50 UTC
https://github.com/mangerlahn/Latest/assets/152599543/2a80aef5-2178-43b3-8d93-94ef69cedea3

After the last update (0.10), I can't update a single app. When I click on Update, the corresponding app opens.

I use MacOS Sonoma 14.1.1 on a Mac mini with Apple M2

**Comment by mangerlahn** [comment] 2023-12-02 21:31
I explained what's going on [here](https://github.com/mangerlahn/Latest/issues/304#issuecomment-1837258079).

TLDR: Latest can't update certain apps itself at the moment. I will clarify that in the UI in the next update and hope to improve updating for these apps in the future. Thanks for the report!

**Comment by mangerlahn** [comment] 2024-02-29 21:43
Duplicate of related #288 and #337

**Closed by mangerlahn** 2024-02-29 21:43 UTC
