### ISSUE TITLE
Final update found display cleaned

### ISSUE THREAD

**Issue by jcbernard83** [mangerlahn/Latest#23] opened 2018-07-30 16:47 UTC
Launch Latest and see some application update added to the list and finally at the end of the scan process, the list is cleaned.

Could you fix it ?

Thanks

**Comment by mangerlahn** [comment] 2018-08-05 14:28
This is a duplicate of #21, that was fixed already. It is not yet in the final app yet, as I continue to work on the update. I try to release that as soon as possible!

**Closed by mangerlahn** 2018-08-05 14:28 UTC
