### ISSUE TITLE
Request: Sort by most recently updated

### ISSUE THREAD

**Issue by hkeely** [mangerlahn/Latest#266] opened 2023-08-10 17:18 UTC
I absolutely love the Latest app! It's a first install on any new machine.

Right now apps are sorted in alphabetical order. What do you think about adding a sort filter so we could see apps in order of most-recently-updated? That would give users a sense of which apps are frequently receiving updates, and which aren't anymore.

**Comment by mangerlahn** [comment] 2023-08-14 08:38
I just realized that there is an older issue, so this is actually a duplicate of #31. I hope to get around to doing this soon :)

**Closed by mangerlahn** 2023-08-14 08:38 UTC
Labels: feature

**Comment by hkeely** [comment] 2023-08-14 14:34
Thank you!!
