### ISSUE TITLE
Add Update für Joplin

### ISSUE THREAD

**Issue by dannykorpan** [mangerlahn/Latest#105] opened 2021-01-21 12:11 UTC
Joplin is a free, open source note taking and to-do application, which can handle a large number of notes organised into notebooks. The notes are searchable, can be copied, tagged and modified either from the applications directly or from your own text editor. The notes are in Markdown format.

Website: https://joplinapp.org/

**Comment by mangerlahn** [comment] 2021-01-31 09:42
This boils down to the same issue described in #19. I currently don't plan to address custom updaters, as there are simply too many apps that would need special attention. Thats nothing I can accomplish on my own. Still hope to find a more general solution for this, but I am closing this as a duplicate of #19 for now.

**Closed** 2021-01-31 09:42 UTC
