### ISSUE TITLE
Cryptomator 

### ISSUE THREAD

**Issue by malbiack** [mangerlahn/Latest#80] opened 2020-04-30 18:53 UTC
I had version 1.5.1 installed and today 1.5.3 came out. The update was not detected

https://cryptomator.org/downloads/

**Comment by mangerlahn** [comment] 2021-01-31 09:46
This boils down to the same issue described in #19. Cryptomator is not supported in Latest as it uses a custom update mechanism. I currently don't plan to address custom updaters, as there are simply too many apps that would need special attention. Thats nothing I can accomplish on my own. Still hope to find a more general solution for this, but I am closing this as a duplicate of #19 for now.

**Closed by mangerlahn** 2021-01-31 09:46 UTC
Labels: bug
