### ISSUE TITLE
Mac App Store apps available on iPad report wrong version number

### ISSUE THREAD

**Issue by luckman212** [mangerlahn/Latest#106] opened 2021-01-23 16:36 UTC
Hi & nice work on Latest 🙌

I installed v.0.7.2 on macOS 11.1 and it reports this update 4.0.4 available for [Copied.app](https://apps.apple.com/us/app/copied/id1026349850)
![image](https://user-images.githubusercontent.com/1992842/105607948-06193380-5d6f-11eb-82b7-1443d4ab3ff3.png)

But AppStore says latest is v4.0.1
![image](https://user-images.githubusercontent.com/1992842/105607963-1af5c700-5d6f-11eb-8ba3-c58ac177614c.png)

Not sure where the version info is coming from?

**Comment by mangerlahn** [comment] 2021-01-23 16:57
Latest seems to receive version information for the iOS version of Copied, which is at 4.0.4. Could you give me the bundle identifier of that app?

You can find it by pasting the following into Terminal.app: 
`/usr/libexec/PlistBuddy -c 'Print CFBundleIdentifier' /Applications/Copied.app/Contents/Info.plist`

**Comment by luckman212** [comment] 2021-01-23 17:19
Oh, interesting. Sure, here's the bundleID of the Mac app:

    com.udoncode.copiedmac

**Comment by mangerlahn** [comment] 2021-01-23 17:48
I check for version information by asking the [iTunes API](https://affiliate.itunes.apple.com/resources/documentation/itunes-store-web-service-search-api/). I ask for Mac Software explicitly. 
Copied is a universal app that ships on iOS and macOS with a single purchase. Somehow the Mac Version is behind (4.0.1 vs 4.0.4). The issue is that since this is a universal purchase, the API returns the information for iOS as well. 

I'll create a Feedback with Apple. If you want to, feel free to report that as well. I am not sure if there is anything else we can do now..

**Comment by mangerlahn** [comment] 2021-11-08 19:00
I have good news regarding this issue! Apple today contacted me with a working fix. There is a new/undocumented value that can be used for the entity parameter. 

Instead of using `entity=macSoftware`, `entity=desktopSoftware` should be used. I tested this with the universal PDF Viewer app and was able to confirm this. 

I plan to implement a fix in the next version of Latest :)

**Comment by luckman212** [comment] 2021-11-08 19:45
Nice, Good find!

**Comment by core-code** [comment] 2021-11-08 22:15
awesom - we spend TSI's on that issue to no avail. good job there!

**Comment by core-code** [comment] 2021-11-09 15:20
i can confirm that `entity=desktopSoftware` solves the issue nicely!

other MAS API bugs remain. for example, lookup fails for some BIDs although they are definitely on the MAS. for example, consider e.g. any of these BIDs:

```
 archibaldindustries.graysanatomypremiumedition 
 com.awem.StarDefender4 
 com.bakno.billiards 
 com.bakno.spacepig 
 com.bakno.spacepiglite 
 com.indeeo.idraw
 uk.co.echomist.quaver 
```

doing a lookup in the usual way

`https://itunes.apple.com/lookup?bundleId=…`

will fail as if the app was not (or no longer) available on the MAS. however they are definitely
1.) available on the MAS as can be seen in their store (both web and app)
2.) those BIDs show up just just fine when searching for the app name with the API ( h`ttps://itunes.apple.com/search?entity=macSoftware&term=…` )
3.) doing a lookup in their private API ( `https://amp-api.apps.apple.com/v1/...` ) also succeeds

**Comment by wilky761** [comment] 2021-12-15 11:43
> I have good news regarding this issue! Apple today contacted me with a working fix. There is a new/undocumented value that can be used for the entity parameter.
> 
> Instead of using `entity=macSoftware`, `entity=desktopSoftware` should be used. I tested this with the universal PDF Viewer app and was able to confirm this.
> 
> I plan to implement a fix in the next version of Latest :)

Hi there,  

Any idea when the next version of Latest is coming out with the fix for this problem? 

Thanks

**Comment by core-code** [comment] 2021-12-17 17:52
after some initial enthusiasm about the `entity=desktopSoftware` workaround, we found some problems. it just-won't-work for some apps.

consider e.g. bundle id  `com.hipsterwhale.crossycastle.macos`

lookup with `entity=macSoftware` is fine, lookup with  `entity=desktopSoftware` tells 'there is no such app'

**Comment by mangerlahn** [comment] 2021-12-26 13:16
I did a quick check and can confirm your observations. However, this seems to only apply to:
- iOS-only apps that run on ARM-based Macs. This seems to be correct behaviour as these apps don't fall into the category "Desktop apps".
- Apple Arcade apps (like the aforementioned Crossy Castle)

Based on that, it would be sufficient to use `macSoftware` as a fallback if `desktopSoftware` does not return any metadata. This fixes misreported update information for Catalyst apps without sacrificing any metadata for certain apps..

Were you able to find apps that don't fall in any of these categories?

**Comment by mangerlahn** [comment] 2021-12-26 13:18
> > I have good news regarding this issue! Apple today contacted me with a working fix. There is a new/undocumented value that can be used for the entity parameter.
> > Instead of using `entity=macSoftware`, `entity=desktopSoftware` should be used. I tested this with the universal PDF Viewer app and was able to confirm this.
> > I plan to implement a fix in the next version of Latest :)
> 
> Hi there,
> 
> Any idea when the next version of Latest is coming out with the fix for this problem?
> 
> Thanks

I am sorry that this still an issue. I hope to be able to have a new version out soon :)

**Comment by core-code** [comment] 2021-12-27 15:18
> Were you able to find apps that don't fall in any of these categories?

i can confirm your findings, this particular issue is limited to AppleArcade games. to recap, asking the MAS API using `entity=desktopSoftware` to compare version numbers with installed apps works fine except for those cases:

• AppleArcade games. this affects around 200 BIDs. the proper workaround is to perform the query using `entity=macSoftware` instead
• the bug where both kinds of lookups either fail or claim that this BID is iOS-only. affects a few dozen BIDs, e.g. `com.bakno.spacepig`
• the general issue that Apple does not force developers to have their actual version numbers align with the marketing version numbers stored in the MAS combined with the issue that the MAS API does not return the *actual* version numbers of the app. this also affects a few hundred BIDs. this can either cause missed updates (marketing version lower) or fake updates (marketing version higher). e.g. `it.nebula.cappuccino`

**Comment by vordenken** [comment] 2022-03-03 12:58
Is there any update to this? I also have this problem and it sounds like there is a fix but it isn't implemented yet?

**Comment by wilky761** [comment] 2022-03-04 07:48
> Is there any update to this? I also have this problem and it sounds like there is a fix but it isn't implemented yet?

Yeh, I'd love to see the fix being implemented also. Thanks

**Comment by mangerlahn** [comment] 2022-03-04 12:18
I finally got around to work on Latest recently. I have this particular fix ready locally and wanted to release that as part of a bigger update. In hindsight I should have pushed the fix before tackling other stuff. Sorry for the delay, this should be out soon :)

**Comment by mangerlahn** [comment] 2022-03-12 10:25
Fixed with f0bb243

**Closed by mangerlahn** 2022-03-12 10:25 UTC
Labels: bug

**Comment by wilky761** [comment] 2022-03-12 10:34
Amazing. But I can only see version 0.7.3 (462). Is there a new version coming out with this fixed?

**Comment by mangerlahn** [comment] 2022-03-12 14:06
Yes, I am currently working on finishing up that new version :)

**Comment by mangerlahn** [comment] 2022-03-12 16:48
Follow up: You should be able to download it now. Feedback appreciated!

**Comment by wilky761** [comment] 2022-03-12 20:34
You've nailed it. Works perfectly. Thanks :)

**Comment by vordenken** [comment] 2022-03-13 14:19
Works great - thanks for your work!
