### ISSUE TITLE
Different numbering of the same version bug

### ISSUE THREAD

**Issue by orangesunny** [mangerlahn/Latest#285] opened 2023-11-28 00:49 UTC
Today’s 0.10 version delivered an obscure conflict of app versions, resulting in nothing to update. The Spitfire in the screenshot is the latest version, originally installed from DMG from the author’s website and then updated via the built-in updater. The long number is probably Homebrew or other new source in 0.10.

<img width="706" alt="Snímek obrazovky 2023-11-28 v 1 43 30" src="https://github.com/mangerlahn/Latest/assets/23450011/8a21e8f1-77c2-4648-ab16-e81410b98cc7">

**Comment by rakalex** [comment] 2023-11-28 06:39
Same issue 

<img width="325" alt="image" src="https://github.com/mangerlahn/Latest/assets/1472809/4cca5e34-93b2-443b-9d1f-912141da381a">

**Comment by martincampbell** [comment] 2023-11-28 08:08
Same for me in version 0.10. Several apps displaying suggested updates of the form:
Your version: A.B.C
New version: A.B.C.D

Where A.B.C are the same and A.B.C.D is the currently installed version.

**Comment by pro-sumer** [comment] 2023-11-28 09:12
I also have a few:

* Parallels Desktop: installed: 19.1.1, Latest: 19.1.1-54734
* IntelliJ IDEA CE: installed: 2023.2.5 (IC-232.10227.8), Latest: 2023.2.5 (232.10227.8)
* Keyboard Maestro installed 11.0.1 (11.0.1), Latest: 11.0.1 (1101)
* p4merge: installed 2023.3 (2023.3/2495381), Latest: 2023.3 (2495381)

**Comment by mangerlahn** [comment] 2023-11-28 09:22
Thanks a lot for these reports! I will go though these lists and see what I can do :)

**Comment by mischnic** [comment] 2023-11-28 14:50
<img width="299" alt="Bildschirm­foto 2023-11-28 um 15 49 15" src="https://github.com/mangerlahn/Latest/assets/4586894/d201bf07-7bda-4511-848d-5e2d9fb7b12f">

(Ignore Firefox. Not sure whats going on with Meld, maybe the rc was just promoted as the release without changing the version)

**Comment by F1248** [comment] 2023-11-28 15:26
Spotify.app:
Your version: 1.2.25.1011.g0348b2ea
New version: 1.2.25.1011

Fig.app:
Your version: 2.17.0-beta.7
New version: 2.17.0

Android File Transfer.app:
Your version: 1.0.12
New version: 5071136

**Comment by WillFulmer** [comment] 2023-11-28 16:05
Similar issue here:
<img width="290" alt="image" src="https://github.com/mangerlahn/Latest/assets/36053224/a7f1a366-115f-47f7-bcc9-0483787360de">

**Comment by orangesunny** [comment] 2023-11-28 17:35
Thanks, @mangerlahn, for this tiny bug. It’s not a showstopper, and introduced me to a few useful apps.

BTW, @F1248, do you know https://github.com/ganeshrvel/openmtp/ ?

**Comment by F1248** [comment] 2023-11-28 20:05
> BTW, @F1248, do you know https://github.com/ganeshrvel/openmtp/ ?

@orangesunny Thanks for the tip, I'll give it a try!

**Comment by streamtree** [comment] 2023-11-28 23:38
I don't think there's a need (or that it's practical) to handle these on a case-by-case basis. Many (if not all) can by handled with some basic parsing rules.

**Comment by jostrasser** [comment] 2023-11-29 07:31
Same here.
Question: what will occur if I "Ignore" the update? Will it permanently ignored or only the actual outstanding update?

Thanks JO!

**Comment by mangerlahn** [comment] 2023-11-29 10:35
Ignore puts the selected app onto an ignore-list, so no updates will be shown for it. You can show ignored apps via View > Show Ignored Apps, from there you can unignore an app.

**Comment by mangerlahn** [comment] 2023-11-29 10:44
> Many (if not all) can be handled with some basic parsing rules.
Definitely not all, I looked into some apps now and it's kind of a mixed bag. Sublime Text, Spotify, MuseScore and others should be fixable by being more flexible with version number detection. For others I just don't know what's going on. 
Warp, Android Studio and others have completely different version information in-app vs. homebrew. Not really sure on how to deal with these.

**Comment by mangerlahn** [comment] 2023-11-29 10:45
@WillFulmer which apps are affected for you? I see the issue with Spotify, is there any other app? (They look legit from the screenshot)

**Comment by martincampbell** [comment] 2023-11-29 20:41
Affected apps:
DiffMerge (via sourcegear.com)
Gramps (via gramps-project.org)
Plex Media Server (via plex.tv)
Plex (via plex.tv)

**Comment by mangerlahn** [comment] 2023-12-02 21:20
Closing this as duplicate of #297. I added all apps brought up here to the list I maintain there. Thanks for reporting!

**Closed by mangerlahn** 2023-12-02 21:20 UTC
Labels: bug

**Comment by WillFulmer** [comment] 2024-02-16 13:33
Good morning @mangerlahn . I know this issue is closed but seeing a new one out there.

On Latest 0.10.3 (1190)
<img width="284" alt="image" src="https://github.com/mangerlahn/Latest/assets/36053224/79c654b8-ac85-4205-89b0-6b8e7e482ef9">

<img width="327" alt="image" src="https://github.com/mangerlahn/Latest/assets/36053224/8bc8efa8-7bd1-40d2-a93e-839aa4c9b362">

<img width="254" alt="image" src="https://github.com/mangerlahn/Latest/assets/36053224/0d6feae3-19ed-4e0c-8657-3a7e2dff2839">
