### ISSUE TITLE
Scans make app appear non-responsive

### ISSUE THREAD

**Issue by gingerbeardman** [mangerlahn/Latest#48] opened 2019-09-02 21:03 UTC
I have a lot of apps, so Latest (0.5 and 0.6) take a long time to show the window.

The icon just bounces (over 27 bounces on first launch) until the scan is complete.
This happens every launch, but subsequent launches are slightly faster (19 bounces).

A better experience would be for the window to appear and then take time to populate?

**Comment by gingerbeardman** [comment] 2019-09-02 21:42
clicking "Reload" also sees the same unresponsive wait

**Comment by mangerlahn** [comment] 2019-09-02 22:02
Mhh, this should not be the case. The app should launch and start the checking process *after* that. I have about 60 apps in my list, not too many, but also not nothing.

**Comment by gingerbeardman** [comment] 2019-09-02 22:10
I have 233 apps. 🤷‍♂️

https://imgur.com/a/8xGvvKf

**Comment by mangerlahn** [comment] 2019-09-02 22:12
This is not normal. I'll take a look!

**Comment by gingerbeardman** [comment] 2019-09-02 22:16
As soon as I launch, Console.app shows lots of Latest network requests, once they stop appearing the main window appears.

**Comment by mangerlahn** [comment] 2019-10-05 00:23
I changed the update checking mechanism. This might fix this problem. Could you try this "beta" and see if it works?
https://max.codes/latest/Latest_0.6.2_Beta.zip

**Comment by gingerbeardman** [comment] 2019-10-05 14:28
With this beta the long, bouncing launch is still there for me (23 bounces).

**Comment by mangerlahn** [comment] 2019-10-06 12:45
I think I understand this problem now. The hang is just a symptom. Even having 200+ apps should not result in such a long scan operation. 

I could fix the symptom, but the check would stay that long. I’d rather attempt to fix the cause, but I have to investigate further on this.

**Comment by mangerlahn** [comment] 2019-10-06 20:33
Ok, I found one thing that might cause the issue. Since I still can't reproduce the issue, I kindly ask you to test this again. https://max.codes/latest/Latest_0.6.2_Beta_2.zip

**Comment by gingerbeardman** [comment] 2019-10-07 10:58
Much faster! (7 bounces, 3 on subsequent launches) 

Also, CPU usage during the scan still makes my computer non-responsive.

**Comment by mangerlahn** [comment] 2019-10-07 18:52
I know where the problem is. Latest collects a list of all apps within the Applications folder prior to checking for updates. To build this list, it has to look at every file in that folder. Apps are just folders themselves. So theoretically there are hundreds of thousands of files to be checked. I can speed ups the process by skipping everything within apps. But somehow something goes through on your machine, resulting in many more files being checked then the 200+ apps you have. 

Would you mind checking whether there are some programs/apps and folders in your applications folder, that are not typical .app files? Maybe I can sort this out then..

**Comment by gingerbeardman** [comment] 2019-10-08 10:51
Let me know how I can send you a directory listing of my Applications folder.

**Comment by mangerlahn** [comment] 2019-10-08 21:45
While building some logging for this, I realised I could optimise further. I think this is as far as I can go, see if it is any better. After that I rework the scan to happen on the background, so that the app won't hang at all.

**Comment by mangerlahn** [comment] 2019-10-08 21:46
If you want to see how many files are scanned, you can open the Console.app and search for the process Latest and the term scan. Then launch Latest to fill the console. Use https://max.codes/latest/Latest_0.6.2_Beta_3.zip for that :)

**Comment by gingerbeardman** [comment] 2019-10-09 15:43
> Scanned 8404 items

Well, there we have it.

What criteria exactly is it scanning?

Interesting entries:

958 of this:
```
default	16:35:56.653405 +0100	Latest	Scanning file:///Applications/Adobe(null)hotoshop
``

836 of this:
```
default	16:35:57.991586 +0100	Latest	Scanning file:///Applications/Adobe2nDesign
```

422 of this:
```
default	16:35:58.544725 +0100	Latest	Scanning file:///Applications/Utilities/Adobe
```

File types being scanned that I would not expect:
- ini
- fch
- jpg
- pdf
- dylib
- bat
- ico
- jar 
- png
- php
- xml

Big folders:
- MAME (roms subfolder)
- MAMP (htdocs subfolder)
- hidden .svn folders
- hidden .git folders

**Comment by mangerlahn** [comment] 2019-10-10 06:56
Okay, thank you very much for this listing. The scan works by asking the system for files, and it will give me them, one by one. I look if that file is an app, otherwise I ignore it. I can't just filter them beforehand. Ill investigate why the Adobe stuff is getting scanned so deep and will ignore hidden folders. I probably can't do anything about the MAMP and MAME folders, but with all the other improvements on hand we still should see a big improvement.

**Comment by mangerlahn** [comment] 2019-10-10 06:57
BTW on my Mac I see ~100 scanned items 😋

**Comment by gingerbeardman** [comment] 2019-10-10 12:19
OK, so there is probably a better method to do your scan.

For example in the shell I do this:
`mdfind -0 -onlyin /Applications/ 'kMDItemKind == "Application"`

You may also want to look into this:
https://github.com/sveinbjornt/KatSearch

**Comment by mangerlahn** [comment] 2019-10-18 23:22
Thats a great idea! I think I have it now, feel free to test: https://max.codes/latest/Latest_0.6.2_Beta_4.zip

**Comment by gingerbeardman** [comment] 2019-10-19 16:22
File not found?

**Comment by mangerlahn** [comment] 2019-10-19 20:13
Sorry, server issues. Should work now!

**Comment by gingerbeardman** [comment] 2019-10-20 15:48
Works a treat, thanks

**Comment by mangerlahn** [comment] 2019-10-20 18:17
Fixed with d3a90da6ad4a59bde072c0dbf632987aa71cde44

**Closed by mangerlahn** 2019-10-20 18:17 UTC
Labels: bug

**Comment by mangerlahn** [comment] 2024-04-05 11:12
I have made an attempt to revert the change implemented to fix this issue. Several people have reported the issue of seeing no apps when launching Latest. My suspicion is that Spotlight is either not enabled or has not indexed apps yet. Going back to iterating over the directories is one option and I feel my current solution is sufficiently efficient. Since you had issues with the old implementation, could you check if this new one works for you?
 [Latest.zip](https://github.com/mangerlahn/Latest/files/14874995/Latest.zip)

**Comment by gingerbeardman** [comment] 2024-04-05 12:00
Several people? How many exactly?  
And how many people are using the app without issue?  
Would the people you mention also complain that the same files in the same scenario are not found in Finder search?

For me this new app behaves as follows:
1. unresponsive on launch
1. (window finally appears)
1. unrepsonsive when scanning
1. (hangs, see image below)
1. wait for ~3 minutes, literally
1. some people would have killed the app by now or filed an issue with you that it's hanging
1. (finally, app comes back to life; shows results — a single one in my case!)

<img width="450" alt="Screen shot 2024-04-05 at 12 50 09" src="https://github.com/mangerlahn/Latest/assets/49612/9ce9f119-a0cf-4cf6-9be6-fa088f458cb2">

- I have ~760 apps at /Applications
- I have ~2394 apps at /
- The current release version of Latest completes a scan in ~5 seconds
- I'm using an M1 Pro 2021

The only situations when an app would not be found, as you say, are
1. when Spotlight is not enabled (which can be detected by you in your app, and presented to the user)
2. when an app has not been indexed in Spotlight (so the check happens in the brief moment after downloading the app and before Spotlight indexes it). One could assume a freshly downloaded app is up-to-date, and even if it's not it will be picked up in the next scan.

Anyway, I strongly disagree with this decision to rollback.

**Comment by mangerlahn** [comment] 2024-04-06 21:43
Thank you for your valuable feedback!

Hangs are my fault, but I am disappointed to hear that loading times are still very high.

If you have the info: How would I detect that users have Spotlight disabled?
I did not check how many users brought this up exactly, but I'd say around a dozen. It appears that for many of them this issue both comes up and resolves after updating macOS. There have been reports that having no apps in Latest is not resolved by restarting the Mac, all that while Spotlight is enabled. I tried to detect this scenario by checking if `NSMetadataQuery` returns any results, and fall back to directory enumeration otherwise. This apparently did not work, I had one PR with someone who had this issue reporting that `NSMetadataQuery`was only reporting Safari. 
If you have another approach at hand that would detect this issue I am happy to hear it.

**Comment by gingerbeardman** [comment] 2024-04-06 22:11
> If you have the info: How would I detect that users have Spotlight disabled?

`$ mdutil -s -v /Volumes/volumename`

> /Volumes/volumename:
>    Indexing enabled.

https://apple.stackexchange.com/a/229420/15281

**Comment by mangerlahn** [comment] 2024-04-08 04:51
[Latest.zip](https://github.com/mangerlahn/Latest/files/14901035/Latest.zip)
Here is an updated build with directory enumeration that should run smoother. I'll continue to investigate this issue. I would assume that checking if Spotlight is enabled is not sufficient. One could disable indexing for applications if I am correct. Plus there are these weird cases were almost no apps are being returned by the metadata query. Asking users if the apps are found via Spotlight / Finder is a good idea.

**Comment by gingerbeardman** [comment] 2024-04-08 12:34
This one doesn't hang my machine. But it's definitely slower to scan and has issues.

But after the scan progress completes the circle, 10 seconds, it sits there for 20 seconds. Total seconds from pressing scan to the circle disappearing is exactly 30 seconds.

<img width="150" alt="image" src="https://github.com/mangerlahn/Latest/assets/49612/aacb7d44-9716-4974-bde0-d8d8d5f7f257">

Also, curiously, no updates were listed!

<img width="1200" alt="Screen shot 2024-04-08 at 13 39 05" src="https://github.com/mangerlahn/Latest/assets/49612/f930bf1a-8ded-489b-88a1-f80cf8ed31fe">

## Contrast

Scanning using the release version, takes only 7 seconds, and shows multiple updates pending.

<img width="1312" alt="Screen shot 2024-04-08 at 13 37 40" src="https://github.com/mangerlahn/Latest/assets/49612/1a516345-ed14-41a2-86d1-0278aaeedf4c">
