### ISSUE TITLE
Latest Big Sur no updates

### ISSUE THREAD

**Issue by Maclife420** [mangerlahn/Latest#119] opened 2021-03-19 23:33 UTC
Since Big Sur on macOS. Latest cannot find any apps anymore. it is just spinning and spinning but nothing happens
<img width="901" alt="Bildschirmfoto 2021-03-20 um 00 32 59" src="https://user-images.githubusercontent.com/67626904/111851534-d4a68980-8913-11eb-9b3c-a40c16476108.png">

**Comment by mangerlahn** [comment] 2021-03-23 14:40
Hi!

Latest uses Spotlight to gather the list of installed apps. It might be that there is a problem with Spotlight on your computer. Please look [here](https://github.com/mangerlahn/Latest/issues/78#issuecomment-633966439) for more details. I hope this helps. 

I plan to improve this, so that the issue no longer occurs, but maybe this helps you in the meantime :)

**Comment by mangerlahn** [comment] 2022-03-12 10:31
Closing as duplicate of #96

**Closed by mangerlahn** 2022-03-12 10:31 UTC
Labels: bug
