### ISSUE TITLE
scan external drives for app updates

### ISSUE THREAD

**Issue by RemoPro** [mangerlahn/Latest#395] opened 2024-09-14 08:15 UTC
I have an external drive where I store many Mac apps that I use on all my Macs. Now it would be great if I could scan the drive for app updates as now its boring to check all manually.

**Comment by mangerlahn** [comment] 2024-09-19 06:31
Thanks for the report! This should be covered by #143, which I already implemented locally. Will be part of the next update :)

**Comment by mangerlahn** [comment] 2024-09-28 12:26
Closed as duplicate of #143

**Closed as completed by mangerlahn** 2024-09-28 12:26 UTC
Labels: feature
