### ISSUE TITLE
Spotify not updating

### ISSUE THREAD

**Issue by alexlouismorlevat** [mangerlahn/Latest#304] opened 2023-12-01 17:40 UTC
Hello,

When I click to update Spotify, it just opens Spotify.

How do I update it?

Thanks

Alex Louis Morlevat

<img width="698" alt="Screenshot 2023-12-01 at 18 39 49" src="https://github.com/mangerlahn/Latest/assets/75369256/5ef60f2d-7b4e-48cd-bce5-605da4622595">

**Comment by mangerlahn** [comment] 2023-12-02 21:29
Hi Alex, thanks for reaching out. There are two issues here on my side, nothing you can do.

First, Latest currently shows an update for Spotify, but there is none, you are on the current version. Further, certain apps like Spotify can't be updated within Latest at the moment. In a future update I will improve the user interface to clarify that. The update button will open Spotify, so that you can update it from there. 

This is also a duplicate of #293.

**Closed** 2023-12-02 21:39 UTC
