### ISSUE TITLE
List of updates clears after the update checker finishes

### ISSUE THREAD

**Issue by jcbernard83** [mangerlahn/Latest#28] opened 2018-08-18 08:32 UTC
Hello,

Thanks for the job !
No more crash at the end of update scan.
However, the list of available updates is cleared at the end of the scan as in 0.40.

Bye,

**Comment by mangerlahn** [comment] 2018-08-19 15:51
Thanks for reporting back to me! 

So the app loads all available updates and then immediately removes all of them from the list after the scan?

**Comment by jcbernard83** [comment] 2018-08-20 17:15
Hi,

Yes sorry it was indeed 0.3.2.

Bye,
JC

**Comment by dennis3484** [comment] 2018-09-07 10:29
Hi @mangerlahn 
First of all, thanks for the great tool!

I'm having this issue with version 0.42 as well (see GIF). Let me know if you need anything else.

![2018-09-07_12-08-20](https://user-images.githubusercontent.com/322536/45214008-8bccdf00-b299-11e8-8117-417f4d2ae082.gif)

Thanks!

**Comment by mangerlahn** [comment] 2018-09-14 13:27
Hi,

thanks for the gif! I could not reproduce this until recently, its really strange and I am still not sure why that happened. I reworked the code that caused the problem. It seems fixed for me, but the issue was occurring not often anyways. Would you like to verify that the issue is fixed? You can download a ready to use version [here](https://max.codes/latest/Latest-beta.zip).

**Comment by ericbn** [comment] 2018-09-14 16:58
I was having the same issue with version 0.4.2, and it was solved for me in the beta linked above.

**Comment by jcbernard83** [comment] 2018-09-14 17:26
Thanks a lot. It works.

**Comment by dennis3484** [comment] 2018-09-14 17:48
The beta version fixes the issue. Thanks!

**Comment by mangerlahn** [comment] 2018-09-14 19:59
Great, I’ll be releasing this ASAP!

**Comment by mangerlahn** [comment] 2018-09-14 20:00
Fixed in de4d01c

**Closed by mangerlahn** 2018-09-14 20:00 UTC
Labels: bug
