### ISSUE TITLE
Crash without network

### ISSUE THREAD

**Issue by Pauldu90** [mangerlahn/Latest#396] opened 2024-09-18 13:04 UTC
The app always crash if I shut down the network connection. I'm on a MacBook Pro M1 with macOS 15.0, but it was the same on macOS 14.x.

**Comment by mangerlahn** [comment] 2024-12-25 13:27
Thanks for the report! Will be fixed with the next update :)
This is a duplicate of #340

**Closed as completed by mangerlahn** 2024-12-25 13:27 UTC
Labels: crash
