### ISSUE TITLE
Handful of false positives

### ISSUE THREAD

**Issue by MrMLK** [mangerlahn/Latest#307] opened 2023-12-02 15:20 UTC
![CleanShot 2023-12-02 at 09 16 49@2x](https://github.com/mangerlahn/Latest/assets/241619/ef927939-5953-4c89-aed5-18576d284a8c)

All three of these  applications say I'm on the latest version.

**Comment by Svec-Tomas** [comment] 2023-12-02 16:14
<img width="262" alt="Snímka obrazovky 2023-12-02 o 16 27 16" src="https://github.com/mangerlahn/Latest/assets/138758322/eab833e2-16cd-498f-954e-0dee89c9ff06">
<img width="395" alt="Snímka obrazovky 2023-12-02 o 16 27 05" src="https://github.com/mangerlahn/Latest/assets/138758322/440cd7be-2c54-448e-a78e-cea45c29a218">
I have the same issue with Webex. I am on the latest version while it detects that I still need to make an update.

**Comment by mangerlahn** [comment] 2023-12-02 21:25
> @MrMLK All three of these applications say I'm on the latest version.

I have Android Studio and Parallels on my list in #297, iStat Menus however appears to be on v. 6.73, so this seems correct.

**Comment by mangerlahn** [comment] 2023-12-02 21:26
@Svec-Tomas That's weird. I just downloaded Webex and it shows it as up-to-date for me. Latest appears to show an old version there. Does restarting Latest help?

**Comment by Svec-Tomas** [comment] 2023-12-02 21:39
No it is not. I have the same issue also with MacUpdater, where I have also Webex with update available, however I am using the latest version, but it shows I still need to update to it.

**Comment by mangerlahn** [comment] 2023-12-02 21:43
Hmm, weird. Since Latest (and probably MacUpdater) request version information for a given app through the system, I would assume that the system returns some old value here. Maybe a Mac reboot does help?

What does QuickLook show for WebEx?
<img width="756" alt="Screenshot 2023-12-02 at 22 42 46" src="https://github.com/mangerlahn/Latest/assets/11056766/50aca7b2-4262-498b-99a8-63f692206af4">

**Comment by MrMLK** [comment] 2023-12-02 22:15
> > @MrMLK All three of these applications say I'm on the latest version.
> 
> I have Android Studio and Parallels on my list in #297, iStat Menus however appears to be on v. 6.73, so this seems correct.

![CleanShot 2023-12-02 at 16 12 25@2x](https://github.com/mangerlahn/Latest/assets/241619/6439e8ad-219b-48e1-be63-ca812a6585f9)

Interesting. iStat thinks its uptodate.

**Comment by Svec-Tomas** [comment] 2023-12-02 22:20
<img width="636" alt="Snímka obrazovky 2023-12-02 o 23 19 15" src="https://github.com/mangerlahn/Latest/assets/138758322/d0ad3e51-2031-4f18-a1ba-7103751195bd">

That's interesting, here it really shows some older version! I will finish some of the work I am currently doing and then I will do restart to check if it helps.

**Comment by Svec-Tomas** [comment] 2023-12-02 22:30
Restart did not helped :( App still says and shows 43 version, Quick Look 42 version, not sure how this is even possible.

**Comment by mrfloris** [comment] 2023-12-04 12:25
Can confirm that sublime text and sublime merge, both licensed, are up to date with the same build number, and show as if there's an update available. 
I also noticed that it incorrectly reports plex media server. I am already up to date, and now after installing latest app it says i am not. checking in the settings of plex media server, it shows the full build number and says i am up to date.

<img width="841" alt="Screenshot 2023-12-04 at 13 19 41" src="https://github.com/mangerlahn/Latest/assets/28841349/1aaa2bca-9597-45f8-9e64-9d75ae2ebdd0">
<img width="813" alt="Screenshot 2023-12-04 at 13 19 18" src="https://github.com/mangerlahn/Latest/assets/28841349/6be63e41-0d52-48ec-8211-d22db7a8969a">
<img width="628" alt="Screenshot 2023-12-04 at 13 19 06" src="https://github.com/mangerlahn/Latest/assets/28841349/f2a9b2d4-e141-4c6a-9b0c-bbcf9901a9a6">
<img width="776" alt="Screenshot 2023-12-04 at 13 24 28" src="https://github.com/mangerlahn/Latest/assets/28841349/3f192ab8-058a-4863-b80f-83348e2bb057">

**Comment by ljara2106** [comment] 2023-12-05 19:05
Yep this is happening after the latest update. it was working fine before.

**Comment by javae** [comment] 2023-12-06 07:40
Same here, lots of false positives, and when I click Update it just opens the app instead of actually trying to update it like before.

**Comment by onegin1** [comment] 2023-12-08 05:48
I am currently using the latest version of the Latest app, and I followed the standard update procedure for Signal. I have attached screenshots for your reference:

<img width="278" alt="image" src="https://github.com/mangerlahn/Latest/assets/79843941/ec6b0629-c57a-403a-ba94-748da67182de">
<img width="499" alt="image" src="https://github.com/mangerlahn/Latest/assets/79843941/15708b51-618c-4566-91a4-7175c57677a4">
<img width="401" alt="image" src="https://github.com/mangerlahn/Latest/assets/79843941/1f8f5eb1-d67f-4508-ac44-22a1bf5026a3">

Despite having updated Signal to the latest version, the Latest app continues to consider it as an app that needs updating.

I have been a satisfied user of Latest, and I must mention that, regardless of this issue, it remains my preferred and perfect application for daily updates.

Could you please look into this matter and provide guidance on resolving the update evaluation discrepancy for Signal? Your prompt attention to this issue is greatly appreciated.

Thank you for your time and assistance.

Best regards

**Comment by mangerlahn** [comment] 2023-12-08 21:00
Looks similar to the WebEx issue above. Could you open quicklook on the Signal app?

**Comment by mangerlahn** [comment] 2023-12-09 22:00
Closing this as duplicate of #297

**Closed by mangerlahn** 2023-12-09 22:00 UTC
