### ISSUE TITLE
Crash when no Internet connection

### ISSUE THREAD

**Issue by sstaub** [mangerlahn/Latest#411] opened 2024-11-22 07:21 UTC
MacBook Pro 13 M1.
After starting my MacBook without connected WLAN the App crashed immediately.
After activating my WLAN the app works.
Thank you for that nice App.

**Comment by mangerlahn** [comment] 2024-12-25 13:28
Thank you for the report, this will be resolved with the next update.
Duplicate of #340

**Closed as completed by mangerlahn** 2024-12-25 13:28 UTC
Labels: crash
