### ISSUE TITLE
auto update to all available updates or having a button to update all 

### ISSUE THREAD

**Issue by krashnakant** [mangerlahn/Latest#351] opened 2024-02-08 14:16 UTC
Hello, 

Possible to have auto update to all out dated button would be really use full. updating 1 by 1 takes time. 

Really appreciate your effort you are making.

BR,Krashna

**Comment by AushevAhmad** [comment] 2024-02-13 11:15
Latest has a button to update all apps (that is possible to update) but it doesn't have an auto update feature, at least yet.

**Comment by mangerlahn** [comment] 2024-02-15 17:35
Currently not all apps are updatable within Latest. The "Update All" button updates all apps that are. There will be a setting soon that allows to filter apps which can't be updated within Latest. Implementing the update mechanism for these apps will take more time.

**Comment by mangerlahn** [comment] 2024-02-29 21:47
Duplicate of #288

**Closed as completed by mangerlahn** 2024-02-29 21:47 UTC
